networks:
  docker_network:
    name: inception
    # https://docs.docker.com/engine/network/drivers/
    driver: bridge 


services:
  NGINX:
  #NOTE: Build
    build: NGINX/
    pull_policy: build
    image: nginx

  #NOTE: Run
    container_name: NGINX

    env_file:
      - .env

    ports:
      - "80:80"

    networks:
        - docker_network

    volumes:
        - WP:/var/www/html

    # depends_on:
    #   wordpress:
    #     condition: service_healthy

    restart: unless-stopped

  MariaDB:
    # docker build -t CONTEXT IMAGE_NAME
    build: MariaDB/
    pull_policy: build
    image: mariadb

    # docker run --name CONTAINER_NAME -p PORT_HOST:PORT_GUEST IMAGE_NAME
    container_name: MariaDB
    env_file:
      - .env

    networks:
        - docker_network

    volumes:
        - DB:/var/lib/mysql

    secrets:
        - mariadb_root_password
        - mariadb_password

    restart: unless-stopped

  WordPress:
    # docker build -t CONTEXT IMAGE_NAME
    build: WordPress/
    pull_policy: build
    image: wordpress

    # docker run --name CONTAINER_NAME -p PORT_HOST:PORT_GUEST IMAGE_NAME
    container_name: WordPress

    env_file:
      - .env

    depends_on:
      MariaDB:
        condition: service_healthy

    networks:
        - docker_network

    volumes:
        - WP:/var/www/html

    secrets:
        - mariadb_root_password
        - mariadb_password
        - wp_admin_password
        - wp_user_password

volumes:
  DB:
    name: DB
    driver: local
    driver_opts:
      type: none
      device: ${HOST_DATA_PATH}
      o: bind

  WP:
    name: WP
    driver: local
    driver_opts:
      type: none
      device: ${HOST_WP_PATH}
      o: bind

secrets:
  mariadb_root_password:
    file: ./mariadb_root_password.secret
  mariadb_password:
    file: ./mariadb_password.secret
  wp_admin_password:
    file: ./wp_admin_password.secret
  wp_user_password:
    file: ./wp_user_password.secret
