services:
  nginx:
    # docker build -t CONTEXT IMAGE_NAME
    build: nginx/
    image: nginx
    
    # docker run --name CONTAINER_NAME -p PORT_HOST:PORT_GUEST IMAGE_NAME
    container_name: nginx
    ports:
      - "443:443"
