FROM debian:bookworm
# Install the application dependencies
RUN apt update
RUN apt install -y mariadb-server mariadb-client galera-4
# First command to launch
#ENTRYPOINT ["entrypoint.sh"]
# Arguments
#CMD ["-g", "daemon off;"]
