#INFO: from: https://oneuptime.com/blog/post/2026-03-31-redis-install-alpine-linux/

bind 0.0.0.0
protected-mode no

maxmemory 128mb
maxmemory-policy allkeys-lru

# Disable persistence — Redis is used as object cache only
save ""
